// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"github.com/mjiee/scaffold-gin/app/pkg/conf"
	"github.com/mjiee/scaffold-gin/app/pkg/db"
)

// Injectors from wire.go:

func initData(confFile2 string) (data, func(), error) {
	config, err := conf.NewConfig(confFile2)
	if err != nil {
		return data{}, nil, err
	}
	gormDB, cleanup, err := db.NewMysql(config)
	if err != nil {
		return data{}, nil, err
	}
	client, cleanup2 := db.NewRedis(config)
	migrateData := newData(gormDB, client)
	return migrateData, func() {
		cleanup2()
		cleanup()
	}, nil
}
